swagger: "2.0"
info:
    title: Stock Option Planner Service
    description: Service for planning stock options including vesting schedules
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /openapi.json:
        get:
            tags:
                - sop
            summary: Download ./gen/http/openapi.json
            operationId: sop#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /plan/{symbol}:
        get:
            tags:
                - sop
            summary: plan sop
            operationId: sop#plan
            parameters:
                - name: symbol
                  in: path
                  description: stock symbol to retrieve plan for
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: integer
                        format: int64
            schemes:
                - http
